In [1]:
%pip install selenium

Requirement already satisfied: selenium in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (4.9.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: trio~=0.17 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from selenium) (0.10.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from selenium) (2022.12.7)
Requirement already satisfied: attrs>=19.2.0 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio~=0.17->selenium) (22.2.0)
Requirement already satisfied: sortedcontainers in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: idna in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sniffio in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio~=0.17->selenium) (1.1.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution - (c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages)

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.expected_conditions import presence_of_element_located
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support import expected_conditions as EC
import warnings
import time 
import string
# import openpyxl
import os

warnings.filterwarnings("ignore")

In [3]:
import pandas as pd
pd.reset_option('display.max_row', None)

In [4]:
df_jakarta = pd.read_csv('jakarta.csv')
df_jakarta

,tahun,nama_provinsi,nama_kabupaten,nama_kecamatan,nama_kelurahan,luas_wilayah_(km2),kepadatan_(jiwa/km2),Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,2015,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. PANGGANG,0.62,10278.58,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. KELAPA,2.58,2539.95,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. HARAPAN,2.45,962.32,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU SLT,P. UNTUNG JAWA,1.03,2191.54,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU SLT,P. TIDUNG,1.07,4714.69,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,2015,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,MUNJUL,1.90,13493.96,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,2015,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,SETU,3.25,6467.46,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,2015,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,BAMBU APUS,3.17,8818.40,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,2015,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,LUBANG BUAYA,3.72,18750.94,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,2015,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,CEGER,3.63,5626.03,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_jakarta = df_jakarta[{'nama_kabupaten', 'nama_kecamatan', 'nama_kelurahan', 'luas_wilayah_(km2)', 'kepadatan_(jiwa/km2)'}]

In [6]:
df_jakarta

,nama_kabupaten,kepadatan_(jiwa/km2),nama_kecamatan,nama_kelurahan,luas_wilayah_(km2)
0,KAB.ADM.KEP.SERIBU,10278.58,KEP. SERIBU UTR,P. PANGGANG,0.62
1,KAB.ADM.KEP.SERIBU,2539.95,KEP. SERIBU UTR,P. KELAPA,2.58
2,KAB.ADM.KEP.SERIBU,962.32,KEP. SERIBU UTR,P. HARAPAN,2.45
3,KAB.ADM.KEP.SERIBU,2191.54,KEP. SERIBU SLT,P. UNTUNG JAWA,1.03
4,KAB.ADM.KEP.SERIBU,4714.69,KEP. SERIBU SLT,P. TIDUNG,1.07
...,...,...,...,...,...
262,JAKARTA TIMUR,13493.96,CIPAYUNG,MUNJUL,1.90
263,JAKARTA TIMUR,6467.46,CIPAYUNG,SETU,3.25
264,JAKARTA TIMUR,8818.40,CIPAYUNG,BAMBU APUS,3.17
265,JAKARTA TIMUR,18750.94,CIPAYUNG,LUBANG BUAYA,3.72
266,JAKARTA TIMUR,5626.03,CIPAYUNG,CEGER,3.63

In [7]:
df_jakarta_new = df_jakarta.copy()

In [8]:
df_jakarta_new['nama_kelurahan'] = df_jakarta['nama_kelurahan'].str.replace("P. ", "PULAU ")

In [9]:
df_jakarta_new['nama_kecamatan'] = df_jakarta['nama_kecamatan'].str.replace("UTR", "UTARA")
df_jakarta_new['nama_kecamatan'] = df_jakarta_new['nama_kecamatan'].str.replace("SLT", "SELATAN")

In [10]:
df_jakarta_new['nama_kecamatan'] = df_jakarta_new['nama_kecamatan'].str.replace("KELAPULAU", "KELAPA")
df_jakarta_new['nama_kecamatan'] = df_jakarta_new['nama_kecamatan'].str.replace("KALI DERES", "KALIDERES")

In [11]:
df_jakarta_new = df_jakarta_new[df_jakarta_new['nama_kelurahan'] != "KAMAL"]

In [12]:
import re

In [13]:
def search_word(text, word, type):
    if (type == "address"): 
        words = text.split(sep=', ')  # Split the text into individual words
    elif (type == "name"):
        words = re.split(r"[', ']", text)
    
    count = 0
    value = False
    # print(words)
    
    for w in words:
        if w == word:
            count+=1
            value = True  # Word found
    return value, count # Word not found

In [ ]:
text = "Starbucks A B C"
search_word(text, "Starbucks", "name")[0]

False

In [ ]:
maps_df = pd.DataFrame()

In [ ]:
def scratch_data (maps_df, jenis, kelurahan, kecamatan): 
    driver.switch_to.default_content()
    searchbox=driver.find_element(By.ID, ('searchboxinput'))

    if (kelurahan == kecamatan): 
        location= f"kelurahan {kelurahan} kecamatan {kecamatan}"
    else: 
        location= f"{kelurahan} {kecamatan}"

    searchbox.send_keys(location)
    searchbox.send_keys(Keys.ENTER)
    time.sleep(2)

    try: 
        kelurahan = driver.find_element(By.CSS_SELECTOR, "[class*=fontHeadlineLarge]").text
        time.sleep(2)
    except NoSuchElementException:
        pass

    searchbox.send_keys(f" {jenis}")
    searchbox.send_keys(Keys.ENTER)
    time.sleep(3)

    entries = driver.find_elements(By.XPATH, "//*[@role='article']")

    for entry in entries:
        name= entry.get_attribute("aria-label")

        if (search_word(name.upper(), jenis.upper(), "name")[0]): 
            link = entry.find_element(By.TAG_NAME, "a")
            
            driver.execute_script("arguments[0].scrollIntoView(true);", link)
            link.click()
            time.sleep(3)

            # Switch to the pop-up window
            for window_handle in driver.window_handles:
                if window_handle != driver.current_window_handle:
                    driver.switch_to.window(window_handle)
                    break

            # driver.switch_to.window(link)
            try: 
                address = driver.find_element(By.CSS_SELECTOR, '[data-item-id = "address"]').get_attribute("aria-label")

            except NoSuchElementException:
                continue
            
            if (kelurahan != kecamatan): 
                if (search_word(address, kelurahan, "address")[0]): 
                    # print(name)
                    # print(address)
                    maps_df = maps_df.append({'Kelurahan': kelurahan, 'Kecamatan': kecamatan, 'Nama Starbucks': name, 'Alamat' : address}, ignore_index= True)
            else:
                if (search_word(address, kelurahan, "address")[0]):
                    if (search_word(address, kelurahan, "address")[1] > 1): 
                        maps_df = maps_df.append({'Kelurahan': kelurahan, 'Kecamatan': kecamatan, 'Nama Starbucks': name, 'Alamat' : address}, ignore_index= True)
        else: continue
    
    searchbox.clear()
    return maps_df

In [ ]:
i = 0

In [ ]:
from selenium.common.exceptions import StaleElementReferenceException
#Loading Selenium Webdriver 
driver= webdriver.Chrome()
wait = WebDriverWait(driver, 5)
 
#Opening Google maps 
driver.get("https://www.google.com/maps")
time.sleep(3)

for index, row in df_jakarta_new.iterrows():
    try: 
        if (index >= i): 
            i = index
            maps_df = scratch_data(maps_df, "Starbucks", row["nama_kelurahan"], row["nama_kecamatan"])
    except StaleElementReferenceException:
        if (index >= i): 
            i = index
            maps_df = scratch_data(maps_df, "Starbucks", row["nama_kelurahan"], row["nama_kecamatan"])

In [ ]:
i = 191

In [ ]:
maps_df

,Kelurahan,Kecamatan,Nama Starbucks,Alamat
0,Petojo Sel.,GAMBIR,Starbucks Cideng,"Alamat: RRF6+VV4, Jl. Cideng Timur, RT.4/RW.6,..."
1,Petojo Sel.,GAMBIR,Starbucks Ba'Be,"Alamat: RRC9+MG2, RT.4/RW.3, Petojo Sel., Keca..."
2,Kb. Klp.,GAMBIR,Starbucks DT Hayam Wuruk,"Alamat: Jl. Hayam Wuruk No.8, RT.6/RW.2, Kb. K..."
3,Gn. Sahari Utara,SAWAH BESAR,Starbucks - Royalton Kemayoran,"Alamat: RRXR+P7V, Jl. Industri Raya, RT.1/RW.7..."
4,Mangga Dua Sel.,SAWAH BESAR,Starbucks RS Husada,"Alamat: Jl. Raya Mangga Besar No.1, RW.1, Mang..."
...,...,...,...,...
144,Halim Perdana Kusumah,MAKASAR,Starbucks Gate 8 Halim Perdanakusuma,"Alamat: PVMP+Q7H, Halim Perdana Kusumah, Kec. ..."
145,Halim Perdana Kusumah,MAKASAR,Starbucks Coffee - Halim Perdanakusuma Airport,Alamat: Jl. Komodor Halim Perdana Kusuma No.15...
146,Cipayung,CIPAYUNG,Starbucks Coffee,"Alamat: Km. 10.6, Cibubur Square 1st Fl Zona B..."
147,Ceger,CIPAYUNG,Starbucks Green Terrace,"Alamat: Jl. Raya Mabes Hankam, Ceger, Kec. Cip..."
148,Ceger,CIPAYUNG,Starbucks Sakura Garden City,"Alamat: MVGQ+MHJ, Jl. Bina Marga, Ceger, Kec. ..."

In [ ]:
maps_df.to_csv("Starbucks di Jakarta Versi New.csv")

# Universitas / Sekolah Tinggi

In [14]:
def search_word_list(text, word_list, type):
    if (type == "address"): 
        words = text.split(sep=', ')  # Split the text into individual words
    elif (type == "name"):
        words = re.split(r"[', ']", text)
    
    count = 0
    value = False
    # print(words)
    
    for word in word_list: 
        for w in words:
            if w == word:
                count+=1
                value = True  # Word found
    return value, count # Word not found

In [ ]:
text = "Starbucks A B C"
search_word_list(text, ["Star", "Bucks", "Starbucks"], "name")[0]

True

In [ ]:
def scratch_data_list (maps_df, jenis, kelurahan, kecamatan, kategori): 
    driver.switch_to.default_content()
    searchbox=driver.find_element(By.ID, ('searchboxinput'))

    if (kelurahan == kecamatan): 
        location= f"kelurahan {kelurahan} kecamatan {kecamatan}"
    else: 
        location= f"{kelurahan} {kecamatan}"

    searchbox.send_keys(location)
    searchbox.send_keys(Keys.ENTER)
    time.sleep(2)

    try: 
        kelurahan_new = driver.find_element(By.CSS_SELECTOR, "[class*=fontHeadlineLarge]").text
        time.sleep(2)
    except NoSuchElementException:
        pass

    searchbox.send_keys(f" {jenis}")
    searchbox.send_keys(Keys.ENTER)
    time.sleep(3)

    entries = driver.find_elements(By.XPATH, "//*[@role='article']")
    kategori_upper = [kat.upper() for kat in kategori] 

    for entry in entries:
        name= entry.get_attribute("aria-label")

        if (name != kelurahan):

            link = entry.find_element(By.TAG_NAME, "a")
            
            driver.execute_script("arguments[0].scrollIntoView(true);", link)
            link.click()
            time.sleep(3)

            # Switch to the pop-up window
            for window_handle in driver.window_handles:
                if window_handle != driver.current_window_handle:
                    driver.switch_to.window(window_handle)
                    break
            
            try: 
                category = driver.find_element(By.CSS_SELECTOR, "[jsaction = 'pane.rating.category']").text
            except NoSuchElementException:
                continue
            if (search_word_list(category.upper(), kategori_upper, "name")[0]): 
                # driver.switch_to.window(link)
                print("Berhasil")
                try: 
                    address = driver.find_element(By.CSS_SELECTOR, '[data-item-id = "address"]').get_attribute("aria-label")

                except NoSuchElementException:
                    continue
                
                if (kelurahan_new != kecamatan): 
                    if (search_word(address, kelurahan_new, "address")[0]): 
                        # print(name)
                        # print(address)
                        maps_df = maps_df.append({'Kelurahan': kelurahan_new, 'Kecamatan': kecamatan, 'Nama Starbucks': name, 'Alamat' : address}, ignore_index= True)
                        print("Data Ditambahkan")
                else:
                    if (search_word(address, kelurahan_new, "address")[0]):
                        if (search_word(address, kelurahan_new, "address")[1] > 1): 
                            maps_df = maps_df.append({'Kelurahan': kelurahan_new, 'Kecamatan': kecamatan, 'Nama Starbucks': name, 'Alamat' : address}, ignore_index= True)
            else: continue
    
    searchbox.clear()
    return maps_df

In [ ]:
univ_df = pd.DataFrame()

In [ ]:
i = 213

In [ ]:
category = ["Universitas", "Perguruan"]
print([kat.upper() for kat in category])

['UNIVERSITAS', 'PERGURUAN']

In [ ]:
from selenium.common.exceptions import StaleElementReferenceException
#Loading Selenium Webdriver 
driver= webdriver.Chrome()
wait = WebDriverWait(driver, 5)
 
#Opening Google maps 
driver.get("https://www.google.com/maps")
time.sleep(3)

category = ["Universitas", "Perguruan"]

for index, row in df_jakarta_new.iterrows():
    try: 
        if (index >= i): 
            i = index
            univ_df = scratch_data_list(univ_df, "Universitas", row["nama_kelurahan"], row["nama_kecamatan"], category)
    except StaleElementReferenceException:
        if (index >= i): 
            i = index
            univ_df = scratch_data_list(univ_df, "Universitas", row["nama_kelurahan"], row["nama_kecamatan"], category)
    except NoSuchElementException: 
        continue
    finally:
        searchbox=driver.find_element(By.ID, ('searchboxinput'))
        searchbox.clear() 
        continue

i = 0

Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil

In [ ]:
univ_df

,Kelurahan,Kecamatan,Nama Starbucks,Alamat
0,Gambir,GAMBIR,Yayan,"Alamat: RR9H+Q9R, Gambir, Kecamatan Gambir, Ko..."
1,Cideng,GAMBIR,Universitas Budi Luhur Kampus Unit Roxy Mas,"Alamat: Pusat Niaga Roxy Mas, Jl. KH. Hasyim A..."
2,Cideng,GAMBIR,Universitas INABA Kampus Jakarta,"Alamat: Jl. Siantar No.6, RW.3, Cideng, Kecama..."
3,Cideng,GAMBIR,STIH PROF GAYUS LUMBUUN,"Alamat: Jl. Talaud Jl. Biak No.1A, RT.10/RW.4,..."
4,Cideng,GAMBIR,Fakultas Ilmu Keperawatan roxy.,"Alamat: Asy'ari, Jl. KH. Hasyim Ashari No.8, R..."
...,...,...,...,...
494,Cibubur,CIRACAS,Sekolah Tinggi Ilmu Kesehatan Mitra RIA Husada,"Alamat: Jl. Karya Bakti No.3, RT.8/RW.7, Cibub..."
495,Susukan,CIRACAS,UNIVERSITAS IPWIJA,"Alamat: 16, Jl. H. Baping No.17, RT.10/RW.6, S..."
496,Susukan,CIRACAS,Pak Idrus,"Alamat: Jl. Asmin No.56, RT.8/RW.3, Susukan, K..."
497,Susukan,CIRACAS,Stikes Jayakarta,"Alamat: Jl. H. Baping No.4, RT.8/RW.6, Susukan..."
498,Susukan,CIRACAS,Akademi Farmasi Mahadhika,"Alamat: Jl. Suci No.9A, RT.1/RW.4, Susukan, Ke..."

In [ ]:
print(i)

213

In [ ]:
univ_df.to_csv("Universitas di Jakarta.csv")

# SMA

In [ ]:
def scratch_data_list_2 (maps_df, jenis, kelurahan, kecamatan, kategori, ketentuan): 
    driver.switch_to.default_content()
    searchbox=driver.find_element(By.ID, ('searchboxinput'))

    if (kelurahan == kecamatan): 
        location= f"kelurahan {kelurahan} kecamatan {kecamatan}"
    else: 
        location= f"{kelurahan} {kecamatan}"

    searchbox.send_keys(location)
    searchbox.send_keys(Keys.ENTER)
    time.sleep(2)

    try: 
        kelurahan = driver.find_element(By.CSS_SELECTOR, "[class*=fontHeadlineLarge]").text
        time.sleep(2)
    except NoSuchElementException:
        pass

    searchbox.send_keys(f" {jenis}")
    searchbox.send_keys(Keys.ENTER)
    time.sleep(3)

    entries = driver.find_elements(By.XPATH, "//*[@role='article']")
    kategori_upper = [kat.upper() for kat in kategori] 
    ketentuan_upper = [ket.upper() for ket in ketentuan]

    for entry in entries:
        name= entry.get_attribute("aria-label")

        if (name != kelurahan):

            link = entry.find_element(By.TAG_NAME, "a")
            
            driver.execute_script("arguments[0].scrollIntoView(true);", link)
            link.click()
            time.sleep(3)

            # Switch to the pop-up window
            for window_handle in driver.window_handles:
                if window_handle != driver.current_window_handle:
                    driver.switch_to.window(window_handle)
                    break
            
            try: 
                category = driver.find_element(By.CSS_SELECTOR, "[jsaction = 'pane.rating.category']").text
            except NoSuchElementException:
                continue

            if ((search_word_list(category.upper(), kategori_upper, "name")[0]) or search_word_list(name.upper(), ketentuan_upper, "name")[0]): 
                # driver.switch_to.window(link)
                print("Berhasil")
                try: 
                    address = driver.find_element(By.CSS_SELECTOR, '[data-item-id = "address"]').get_attribute("aria-label")

                except NoSuchElementException:
                    continue
                
                if (kelurahan != kecamatan): 
                    if (kelurahan.split(", ")) == 1:
                        if (search_word(address.upper(), kelurahan.upper(), "address")[0]): 
                            maps_df = maps_df.append({'Kelurahan': kelurahan, 'Kecamatan': kecamatan, 'Nama SMA': name, 'Alamat' : address}, ignore_index= True)
                            print("Data Ditambahkan")
                    else:
                        if (search_word(address.upper(), kelurahan.split(", ")[0].upper(), "address")[0]): 
                            maps_df = maps_df.append({'Kelurahan': kelurahan, 'Kecamatan': kecamatan, 'Nama SMA': name, 'Alamat' : address}, ignore_index= True)
                            print("Data Ditambahkan")
                else:
                    if (search_word(address.upper(), kelurahan.upper(), "address")[0]):
                        if (search_word(address.upper(), kelurahan.upper(), "address")[1] > 1): 
                            maps_df = maps_df.append({'Kelurahan': kelurahan, 'Kecamatan': kecamatan, 'Nama SMA': name, 'Alamat' : address}, ignore_index= True)
            else: continue
    
    searchbox.clear()
    return maps_df

In [ ]:
"Gambir Utara, Kecamatan A B C, Kabupaten C".split(", ")

['Gambir Utara', 'Kecamatan A B C', 'Kabupaten C']

In [ ]:
search_word("7J27+X95, PULAU PANGGANG, Kepulauan Seribu Utara, Kab. Administrasi Kepulauan Seribu, Daerah Khusus Ibukota Jakarta 14530", "PULAU PANGGANG", "address")

(True, 1)

In [ ]:
len("Pulau Panggang".split())

2

In [ ]:
sma_df = pd.DataFrame()

In [ ]:
from selenium.common.exceptions import StaleElementReferenceException, ElementNotInteractableException
#Loading Selenium Webdriver 
driver= webdriver.Chrome()
wait = WebDriverWait(driver, 5)
 
#Opening Google maps 
driver.get("https://www.google.com/maps")
time.sleep(3)

category = ["Sekolah Menengah Atas", "Atas", "Umum", "Kejuruan"]
keterangan = ["SMA", "SMAN", "MA", "MAN", "SMK", "SMKN", "SMU", "SMAK", "ATAS"]

for index, row in df_jakarta_new.iterrows():
    try: 
        if (index >= i): 
            i = index
            sma_df = scratch_data_list_2(sma_df, "Sekolah Menengah Atas", row["nama_kelurahan"], row["nama_kecamatan"], category, keterangan)
    except StaleElementReferenceException:
        if (index >= i): 
            i = index
            sma_df = scratch_data_list_2(sma_df, "Sekolah Menengah Atas", row["nama_kelurahan"], row["nama_kecamatan"], category, keterangan)
    except NoSuchElementException: 
        continue
    except ElementNotInteractableException:
        if (index >= i): 
            i = index
            sma_df = scratch_data_list_2(sma_df, "Sekolah Menengah Atas", row["nama_kelurahan"], row["nama_kecamatan"], category, keterangan)
    # finally:
    #     searchbox=driver.find_element(By.ID, ('searchboxinput'))
    #     searchbox.clear() 
    #     continue

i = 0

Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil

In [ ]:
i = 0

In [ ]:
sma_df

,Kelurahan,Kecamatan,Nama SMA,Alamat
0,"Pulau Panggang, Kepulauan Seribu Utara, Kepula...",KEP. SERIBU UTARA,SMA NEGERI 69 JAKARTA Kepulauan Seribu,"Alamat: 7J27+X95, Pulau Panggang, Kepulauan Se..."
1,Pulau Tidung,KEP. SERIBU SELATAN,SMK NEGERI 61 Kepulauan Seribu,"Alamat: 5GX5+4Q8, Pulau Tidung, Kec. Kepulauan..."
2,Pulau Tidung,KEP. SERIBU SELATAN,ASRAMA SMKN 61 JAKARTA,"Alamat: JLN PANTAI SELATAN No.1, Pulau Tidung,..."
3,Gambir,GAMBIR,SMA Negeri 4 Jakarta,"Alamat: Jl. Batu III No.3, RT.7/RW.1, Gambir, ..."
4,Petojo Utara,GAMBIR,SMAN 25 Jakarta,Alamat: Jalan A.M Sangaji No. 22-24 Petojo Uta...
...,...,...,...,...
458,Bambu Apus,CIPAYUNG,Nizamia Andalusia High School (NHS),"Alamat: Jl. Raya Mabes Hankam No.100, RT.2/RW...."
459,Lubang Buaya,CIPAYUNG,Sekolah Menengah Kejuruan Islam Al-Makiyah,"Alamat: Jl. Gorda No.RT01/01, Lubang Buaya, Ke..."
460,Lubang Buaya,CIPAYUNG,SMAN 113 Jakarta,"Alamat: Jl. Al.Baidho I No.10, RT.10/RW.9, Lub..."
461,Lubang Buaya,CIPAYUNG,SMA PGRI 24,"Alamat: Jalan SMPN 157 No.33, RT.2/RW.6, Luban..."
462,Lubang Buaya,CIPAYUNG,Sekolah Menengah Kejuruan Jakarta Raya 2,"Alamat: Jl. Raya Pd. Gede No.36, RT.11/RW.1, L..."

In [ ]:
sma_df.to_csv("SMA di Jakarta.csv")

In [ ]:
print(i)

194

# Tempat Perbelanjaan

In [15]:
def scratch_data_list_shop (maps_df, jenis, kelurahan, kecamatan, kategori): 
    driver.switch_to.default_content()
    searchbox=driver.find_element(By.ID, ('searchboxinput'))

    if (kelurahan == kecamatan): 
        location= f"kelurahan {kelurahan} kecamatan {kecamatan}"
    else: 
        location= f"{kelurahan} {kecamatan}"

    searchbox.send_keys(location)
    searchbox.send_keys(Keys.ENTER)
    time.sleep(2)

    try: 
        kelurahan = driver.find_element(By.CSS_SELECTOR, "[class*=fontHeadlineLarge]").text
        time.sleep(2)
    except NoSuchElementException:
        pass

    searchbox.send_keys(f" {jenis}")
    searchbox.send_keys(Keys.ENTER)
    time.sleep(3)

    sidebar = driver.find_element(By.XPATH, "//*[@role='feed']")

    # Scroll until the desired text is visible
    while True:
        driver.execute_script("arguments[0].scrollTop = arguments[0].scrollHeight;", sidebar)
        
        try:
            end_text_element = WebDriverWait(driver, 10).until(EC.visibility_of_element_located((By.XPATH, '//*[contains(text(), "Anda telah mencapai akhir daftar")]')))
            break  # Break the loop if the text is found
        except:
            pass  # Continue scrolling if the text is not found
    
    entries = driver.find_elements(By.XPATH, "//*[@role='article']")
    kategori_upper = [kat.upper() for kat in kategori] 
    
    # Continue with other operations on the page if needed
    for entry in entries:
        name= entry.get_attribute("aria-label")

        if (name != kelurahan):

            link = entry.find_element(By.TAG_NAME, "a")
            
            driver.execute_script("arguments[0].scrollIntoView(true);", link)
            link.click()
            time.sleep(3)

            # Switch to the pop-up window
            for window_handle in driver.window_handles:
                if window_handle != driver.current_window_handle:
                    driver.switch_to.window(window_handle)
                    break
            
            try: 
                category = driver.find_element(By.CSS_SELECTOR, "[jsaction = 'pane.rating.category']").text
            except NoSuchElementException:
                continue

            if (search_word_list(category.upper(), kategori_upper, "name")[0] and (search_word(name, "Bintang", "name")[0] == False)): #or search_word_list(name.upper(), ketentuan_upper, "name")[0]): 
                # driver.switch_to.window(link)
                print("Berhasil")
                if (name != "88Bintang Perdana II"): 
                    try: 
                        rating = entry.find_element(By.CSS_SELECTOR, "[aria-label*='Bintang ']").text
                        print(rating)
                    except NoSuchElementException:
                        rating = "0,0"
                        continue
                    
                    if (float(rating[:2].replace(",", ".")) > 3.0): 
                        try: 
                            address = driver.find_element(By.CSS_SELECTOR, '[data-item-id = "address"]').get_attribute("aria-label")

                        except NoSuchElementException:
                            continue
                        
                        if (kelurahan != kecamatan): 
                            if (kelurahan.split(", ")) == 1:
                                if (search_word(address.upper(), kelurahan.upper(), "address")[0]): 
                                    maps_df = maps_df.append({'Kelurahan': kelurahan, 'Kecamatan': kecamatan, 'Nama': name, 'Alamat' : address}, ignore_index= True)
                                    print("Data Ditambahkan")
                            else:
                                if (search_word(address.upper(), kelurahan.split(", ")[0].upper(), "address")[0]): 
                                    maps_df = maps_df.append({'Kelurahan': kelurahan, 'Kecamatan': kecamatan, 'Nama': name, 'Alamat' : address}, ignore_index= True)
                                    print("Data Ditambahkan")
                        else:
                            if (search_word(address.upper(), kelurahan.upper(), "address")[0]):
                                if (search_word(address.upper(), kelurahan.upper(), "address")[1] > 1): 
                                    maps_df = maps_df.append({'Kelurahan': kelurahan, 'Kecamatan': kecamatan, 'Nama': name, 'Alamat' : address}, ignore_index= True)
                                    print("Data Ditambahkan")
                    rating = "0,0"
            else: continue
    
    searchbox.clear()
    return maps_df

In [151]:
rating = "0,0 "
print(float(rating[:2].replace(",", ".")))

0.0

In [ ]:
float("Bintang 4,8".split( )[1].replace(",", ".")) > 3.0

True

In [174]:
search_word("Bintang Safety Kenari", "Bintang", "name")

(True, 1)

In [171]:
print(y != "Bintang" for y in "Bintang Safety Kenari".split())

<generator object <genexpr> at 0x000001262B17CE40>

In [16]:
i = 0
toko_df = pd.DataFrame()

In [ ]:
search_word_list("PUSAT PERBELANJAAN", (i.upper() for i in ["Pusat Perbelanjaan", "Perbelanjaan", "Toko"]), "name")

(True, 1)

In [ ]:
list_error = ["PT. Bintang Nero Pratama", ""]

In [18]:
from selenium.common.exceptions import StaleElementReferenceException, ElementNotInteractableException
#Loading Selenium Webdriver 
driver= webdriver.Chrome()
wait = WebDriverWait(driver, 5)
 
#Opening Google maps 
driver.get("https://www.google.com/maps")
time.sleep(3)

category = ["Pusat Perbelanjaan", "Perbelanjaan", "Toko"]

for index, row in df_jakarta_new.iterrows():
    try: 
        if (index >= i): 
            i = index
            toko_df = scratch_data_list_shop(toko_df, "Pusat Perbelanjaan", row["nama_kelurahan"], row["nama_kecamatan"], category)
    except StaleElementReferenceException:
        if (index >= i): 
            i = index
            toko_df = scratch_data_list_shop(toko_df, "Pusat Perbelanjaan", row["nama_kelurahan"], row["nama_kecamatan"], category)
    except NoSuchElementException: 
        continue
    except ElementNotInteractableException:
        if (index >= i): 
            i = index
            toko_df = scratch_data_list_shop(toko_df, "Pusat Perbelanjaan", row["nama_kelurahan"], row["nama_kecamatan"], category)
    # finally:
    #     searchbox=driver.find_element(By.ID, ('searchboxinput'))
    #     searchbox.clear() 
    #     continue

i = 0

Berhasil
Berhasil
Berhasil
Berhasil
5,0(3)
Data Ditambahkan
Berhasil
5,0(3)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
4,4(31.063)
Data Ditambahkan
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
4,6(3.222)
Data Ditambahkan
Berhasil
3,9(9)
Berhasil
Berhasil
Berhasil
Berhasil
4,5(2)
Data Ditambahkan
Berhasil
Berhasil
3,0(3)
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
4,5(6)
Data Ditambahkan
Berhasil
5,0(4)
Data Ditambahkan
Berhasil
4,4(17)
Data Ditambahkan
Berhasil
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
4,5(4)
Data Ditambahkan
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
4,1(42)
Data Ditambahkan
Berhasil
4,5(2)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
3,7(3)
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
5,0(1)
Berhasil
4,3(27)
Data Ditambahkan
Berhasil
5,0(4)
Data Ditambahkan
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
Berhasil
5,0(2)
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
4,5(41)
Data Ditambahkan
Berhasil
Berhasil
4,7(19)
Data Ditambahkan
Berhasil
Berhasil
4,8(6)
Data Ditambahkan
Berhasil
5,0(4)
Data Ditambahkan
Berhasil
4,8(4)
Data Ditambahkan
Berhasil
5,0(4)
Data Ditambahkan
Berhasil
Berhasil
4,3(4)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
Berhasil
5,0(2)
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
5,0(3)
Data Ditambahkan
Berhasil
5,0(8)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
5,0(3)
Berhasil
4,5(2)
Data Ditambahkan
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
3,0(1)
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
4,7(9)
Data Ditambahkan
Berhasil
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
Berhasil
4,9(8)
Data Ditambahkan
Berhasil
5,0(5)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
4,5(6)
Data Ditambahkan
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
4,5(44.196)
Berhasil
Berhasil
Berhasil
4,9(9)
Data Ditambahkan
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
4,6(3.218)
Data Ditambahkan
Berhasil
3,7(3)
Berhasil
5,0(4)
Berhasil
4,6(10.100)
Berhasil
4,0(1)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
5,0(1)
Berhasil
4,0(1)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
Berhasil
4,6(3.222)
Data Ditambahkan
Berhasil
Berhasil
4,4(31.063)
Data Ditambahkan
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
Berhasil
4,5(4)
Data Ditambahkan
Berhasil
3,7(3)
Berhasil
Berhasil
5,0(1)
Data Ditambahkan
Berhasil
Berhasil
5,0(7)
Data Ditambahkan
Berhasil
4,5(6)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
Berhasil
5,0(6)
Data Ditambahkan
Berhasil
Berhasil
5,0(2)
Data Ditambahkan
Berhasil
Berhasil
Berhasil
3,0(1)
Berhasil
Berhasil
3,9(9)
Berhasil
Berhasil
4,5(6)
Data Ditambahkan
Berhasil
Berhasil
4,4(7)
Berhasil
3,0(3)
Berhasil
4,1(42)
Berhasil
4,0(38)
Berhasil
4,4(17)
Berhasil
4,5(2)
Berhasil
5,0(1)
Berhasil
4,0(1)
Data Ditambahkan
Berhasil
5,0(1)
Berhasil
Berhasil

In [42]:
print(i)

157

In [17]:
# 20 Juni
i = 157 # start dari i=125 pokoknya

In [43]:
toko_df

,Kelurahan,Kecamatan,Nama,Alamat
0,Kec. Palmerah,PALMERAH,Plaza Slipi Jaya,"Alamat: Jl. Letjen S. Parman, RT.14/RW.1, Kema..."
1,Kec. Palmerah,PALMERAH,Tk.hengky,"Alamat: RT.5/RW.16, Palmerah, Kec. Palmerah, K..."
2,Kec. Palmerah,PALMERAH,Toko Maspri,"Alamat: Jl. Kemanggisan Pulo No.35, RT.7/RW.9,..."
3,Kec. Palmerah,PALMERAH,POI Slipi Jaya (LM Slipi),"Alamat: Jl. Letjen S. Parman Blok J No.14, RT...."
4,Kec. Palmerah,PALMERAH,Toko minuman zidan,"Alamat: Jl. Palmerah Bar. IX No.52, RT.6/RW.10..."
...,...,...,...,...
473,Kuningan Bar.,MAMPANG PRAPATAN,Warung pak Rebo,"Alamat: Jl. Rengas 1 No.34, RT.10/RW.5, Kuning..."
474,Kuningan Bar.,MAMPANG PRAPATAN,Stokis Oryza Group Jakarta,"Alamat: Jl. Poncol Jaya No.35, RT.14/RW.5, Kun..."
475,Kuningan Bar.,MAMPANG PRAPATAN,MTen / Menara Tendean,"Alamat: Jl. Kapten Tendean No.20C, RW.3, Kunin..."
476,Kuningan Bar.,MAMPANG PRAPATAN,TOKO SANTI CELL / SANTI MART,"Alamat: Jl. Kuningan Barat Raya No.3, RW.1, Ku..."
477,Kuningan Bar.,MAMPANG PRAPATAN,Stokis HPAI Jakarta Selatan,"Alamat: Jl. Kuningan Bar. 1 No.5, RT.12/RW.1, ..."

In [39]:
toko_df.iloc[302]

Kelurahan                                            Manggarai
Kecamatan                                                TEBET
Nama                                                  RR store
Alamat       Alamat: QVP4+WW7, RT.10/RW.1, Manggarai, Kec. ...
Name: 302, dtype: object

In [191]:
toko_df.to_csv("Toko di Jakarta.csv")

In [44]:
toko_df[428:478].to_csv("Toko di Jakarta.csv", mode='a', header=False, index=False)

In [ ]:
# # Set the maximum time to wait for new data to load
# wait = WebDriverWait(driver, 5)

# # Specify a locator for an element that appears after scrolling and new data is loaded
# locator = (By.XPATH, "//*[@role='article']")

# # Function to scroll to the bottom of the page
# def scroll_to_bottom():
#     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

# # Function to check if new data is loaded
# def is_new_data_loaded():
#     try:
#         wait.until(EC.visibility_of_element_located(locator))
#         return True
#     except:
#         return False

# # Scroll and extract data
# data = []

# while True:
#     # Scroll to the bottom of the page
#     scroll_to_bottom()
    
#     # Wait for new data to load
#     if is_new_data_loaded():
#         # Extract the data from the page
#         data_elements = driver.find_elements(By.XPATH, "//*[@role='article']")
#         for element in data_elements:
#             data.append(element.text)
#     else:
#         # No more data is loaded, exit the loop
#         break

In [ ]:
# # Manually scroll through the page to load results
# scroll_pause_time = 1  # Adjust the pause time between scrolls as needed
# scroll_count = 10  # Adjust the number of scrolls to load more results as needed

# for _ in range(scroll_count):
#     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
#     time.sleep(scroll_pause_time)

In [ ]:
# scroll_container = driver.find_element(By.CSS_SELECTOR, "[attribute_name*='::-webkit-scrollbar']")
# scrollable_height = driver.execute_script("return arguments[0].scrollHeight", scroll_container)
# current_scroll_position = 0
# print(scrollable_height)

# while current_scroll_position < scrollable_height:
#     # Scroll to the bottom of the container
#     driver.execute_script("arguments[0].scrollTop = arguments[0].scrollHeight", scroll_container)
#     time.sleep(1)  # Wait for the new results to load
#     current_scroll_position = scrollable_height
#     scrollable_height = driver.execute_script("return arguments[0].scrollHeight", scroll_container)

In [ ]:

    # driver.close()
    # adress= entry.find_element(By.CLASS_NAME, 'section-result-location').text
    # phone = entry.find_element(By.CLASS_NAME, 'section-result-hours-phone-container').text.split(' · ')[-1]
    # print(name)
    # try:
    #     webcontainer= entry.find_element(By.CLASS_NAME, 'section-result-action-container')
    #     website=entry.find_element(By.TAG_NAME, 'a').get_attribute("href")
    # except NoSuchElementException:
    #     website="No website could be found"
    # print (name)
    # print (website)
       
 
    #Try/except  to write the extracted info in the Excel file pass if doessn't exist 
    # try:
    #     maps_df.append(pd.Series([location,name,adress,phone,website]))
    # except IndexError:
    #     pass

Starbucks DT Hayam Wuruk
Alamat: Jl. Hayam Wuruk No.8, RT.6/RW.2, Kb. Klp., Kecamatan Gambir, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10120
Starbucks
Alamat: RT.1/RW.10, Kramat Pela, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12130
Starbucks
Alamat: Jl. M.H. Thamrin No.9, RT.2/RW.1, Kb. Sirih, Kec. Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10340
Starbucks
Alamat: Jl. Letjen M.T. Haryono No.9, RT.11/RW.5, Tebet Bar., Jakarta, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12810
Starbucks Cik Ditiro
Alamat: Jl. Teuku Cik Ditiro No.33, RW.5, Menteng, Kec. Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10310
Starbucks
Alamat: Cyber 2, Lantai GF, Blok X-5 Kav 1-2, Jl. H. R. Rasuna Said, RT.7/RW.2, Kuningan, Kuningan Tim., Kecamatan Setiabudi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12950
Starbucks Plaza Indonesia Lv 4
Alamat: M.H., Jl. K.H. Wahid Hasyim No.15, RT.7/RW.5, Gondangdia, Menteng, Central Jakarta City, Jakarta 10350